#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Tank = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABzNJ"
    "REFUWIXtl2lsFdcVx//n3lme32Y/22DHGAw2fpSw2BAWs6SChLSpE0FoKFVKAxQkyELYHBFC"
    "QaEiakoEIpRQiRTaSm0TEVEMJaFKoVJCaMuWAAXSkgSzOrYf9uOt897Mm5nTD7EpUEhKpYoP"
    "6ZGOztXMuef8NHPuXzPEzLiTJu5o968UQE3N4afvKMDMma823FGAoiLt9M2uK/9twSmPNtDj"
    "08u5pnYYWjpqq4IFF62Xfvwr4cnzoCbcncc9OEP+/Whd7siRikuLFz+2saSETy9ZMgETJ57R"
    "xo49a3XVods9huvXN5LrHOJQSMOevU/c91D9mnkfHv1krKqqWfr8iVJXbZBrzXvqW78+cSr5"
    "SCJx8mhFxfEfjBjxoQMARIQDB39y+wDPPTcNlrWjuLZ27ta3dr1z3xflFhQE4PPloaCgAJZl"
    "me0dycup+OYV23eG3qioaLA2bwnzFwIQERp3vIRsBli0aJPS0nLWBoDXf7v0UGPjruEP1o9x"
    "M2nLscycjCVSkGSQYWRhZLLIdEbDyMJxXHi9HnjzPMjzFpNHXf2NSMe8PYNOB+UtZ4CIwMz4"
    "zncn4PFpD+OBCb3tw4eX5J8+Tb/fueOt4X369MqdOnlOOLarWDkL/ap7kW0DJAQLISCEAHVG"
    "w8gilTLgui4CQYFAfsPoC83mnrXvj1K/dAj7DXmg+6RJiyJTHr2bX179NgDgnmH9czWD+6vX"
    "5m3btg/RaAb3ju1BshNCdnrX2jCyyM/349yFtqdfWf/mK6sWzo7fFGDYsMEIf60XiAgAIqNH"
    "+XjWrG9fm6IuWPAamLkrBwBQWVWGgN8LKQUJIVjKz5sL2QkiBS5duox0KhPc8OqCj/6wd83S"
    "W85AVdWRp5qahv9s4sND+Ykn6zF/wSb3p+vnivnzN4GIMGRoBWprKnD+YjtG3NMHPXoUXvfe"
    "M/+KbBhZdERtymRMhArz2TRzFAx6cfasdf0pKArt/t6GDX8Z/NcDB0ddam6tzaRz+mctMc0f"
    "yOMVy78vXnxxHcrKyln3aJBCkKpqGDSwD4QQGDqk+tqmV0FOnGxB1rTY49FR0asUtmOhLZIE"
    "u5KLi0M2MTM2vzax4ZMz7rPhfuWlHe1xHDxwDCdONSMSSXLdiO5QVEmpZJotywYRkcsMdpmF"
    "EKQoEkQCRAAzwbFtBIIBVIcr0doSB7ODQYP7wzAyIBLc3h6jUCjIFy624aH68SzPNe3a2aO8"
    "+plBA3v608kWfHD0vF3UrciNRtMoKibyeVUwSwSDQQQDAfL6vAgE/PD7fSSlAtdlOI4D27bh"
    "ODZcl1FQEIAnLwAiAU3T4Lg2mpsv40xTC8rLS9Ha2o6Az++CbUlbty7kROwyBJkAgA+OXeZY"
    "LIlRdQPprrJikFCg6yqEELBtG7mcDWYXrsMwLQvZrIlsxkQimUa0PYrTH5+BrvsxcEAl4gkD"
    "ibgB08rB6/GwzYxwuAyaqrpjRtdIw1DfpbVrp9kjh1XKs+ea8dE/WjmbMVFZVU61Q/qxadpw"
    "HAe5nE2u67LtOESdGuG6DCKGrnsgBAEgFBYGsX//McSiCRQVeZGIG4gn0ojFMuywQCCgIpkw"
    "efy4wRzpSOd2v3PkmzRhfIWdHwqQVASpigpd1zB85AAATH6/j3VdhaoqkFJAUSSkFFeFynEc"
    "CCHhui6kFEilDDp08BSPrgtTV/N4wkBTU4TjyQx6lhdi4KBqu+WzdnXqlPp1fcMzFyvdSovk"
    "lSsxSEG2pntkJBLFp59eIH8gjzVdI01RoKgKe70eeHSNNE2D1++Brmvw6BryvB54PBq8Xg/H"
    "YknO5RwUhgKQUkIqAobpAnBR3bcE/cK93YxpynjcbOsbnrkYAJQB/av3Hjx8ckQ8lgh6cpSL"
    "XrHF2fMRwHUoz6uxphCrqiRdV1jXFVdRCKqmkBCCpBCk6zo0TSGpSAgQqZrKW375R3R0JOD1"
    "abDMHA8cHEbP8m5wXMeNRdNqY+PGdatXd0p+lw5U9a06ZWWjd1f1LUVrq422SBvsnAkhCemU"
    "aToONCKQogKqAiiKgJQETZNQNQlVJVdVwFKRbmXvu6CqikynM8TMmPTI11Hes8Rp3L5PVlf3"
    "OLx8+e9GdmmPAgA+nxdEbeMaGtYsPn78z/d2L3G7JeJ5oZISv5wzZ+LbY8YsnQ4AkydPfOy9"
    "9/aXFReHKlMpoxeAntmsFboSSwcJ7JOSVCuXlXYuirq6CiZiTiUNRK8kUVpayKWlRdQS2f3y"
    "dZLLzFg491nqWjMzVq5cqQwdOqNk27ubypgZW36x/Oq9W/mTz0yuP/a392etWvWjZfffP2p1"
    "95JgurTUzxW98p2pU4dmn3++3t29+4V9N+77t0JdtmzZbPzm9R+COYY3+/9JfBnAjT5nzuwV"
    "BQUFSU3TjaqqIp4+fSzfLO+2v4huxzb+fEZNtDVb8vEZs+fO7S8YicSQN27M+Z8C/Cf21fkz"
    "+j/Areyf3IewXAyTH6wAAAAASUVORK5CYII=")
getTankData = Tank.GetData
getTankImage = Tank.GetImage
getTankBitmap = Tank.GetBitmap
getTankIcon = Tank.GetIcon

